name: Branch Name
on:
  pull_request:
    types: [opened]
  create:
  push: 
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1.0.2
        with:
          branch_pattern: '^(feature|fix|hotfix|docs)\/[a-z0-9-]+$'
          comment_for_invalid_branch_name: 'ERROR: This branch doesnt follow the branch-naming rules for this project'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'main'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
